<?php

namespace Tests\Feature;

use App\Models\Brand;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BrandGetAPITest extends TestCase
{

    // TODO: 要修正！ 10/15 15:42
  
    protected function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
  
      $this->brand = factory(Brand::class, 5)->create();
  
    }
  
  
  /**
     * @test
     */
    public function _全ての通貨カラムを取得する()
    {
      $response = $this->json('GET', route('get_brands'));
  
      $response
          ->assertStatus(200)
          ->assertJsonCount(10, 'id');
    }
    
    // /**
    //  * @test
    //  */
    // public function _指定の通貨名を取得する()
    // {
    //   $response = $this->json('GET', route('get_brands.brand_id'), [
    //       'name' => $this->brand->name
    //   ]);
    //
    //   $response
    //       ->assertStatus(200)
    //       ->assertJson(['name' => $this->brand->name]);
    // }
}
