<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LoginApiTest extends TestCase
{
    use RefreshDatabase;
    
    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      
      // テストユーザーの作成
      $this->user = factory(User::class)->create();
    }
  
    /**
     * @test
     */
    public function _LOGIN_登録済みユーザーを認証しレスポンス()
    {
        $response = $this->json('POST', route('login'), [
            'email' => $this->user->email,
            'password' => 'password',
        ]);
        
        $response
            ->assertStatus(200)
            ->assertJson(['name' => $this->user->name]);
      
        // 認証済みであることの確認
        $this->assertAuthenticatedAs($this->user);
    }
}
