<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class LogoutApiTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      
      $this->user = factory(User::class)->create();
    }
  
    /**
     * @test
     */
    public function _認証済みユーザーをログアウトさせる()
    {
      $response = $this->actingAs($this->user)->json('POST', route('logout'));
      
      $response->assertStatus(200);
      $this->assertGuest();
    }
}
