<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

class UserGetApiTest extends TestCase
{
    // テスト時にテスト用DBをリセットする(マイグレーションを実行し直す)
    use RefreshDatabase;
    
    protected function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub
      
      // テストユーザー作成
      $this->user = factory(User::class)->create();
    }
  
    /**
     * @test
     */
    public function _現在ログイン中のユーザー情報のレスポンスAPI()
    {
      $response = $this->actingAs($this->user)->json('GET', route('user'));
      
      $response
          ->assertStatus(200)
          ->assertJson([
              'id' => $this->user->id,
          ]);
    }
    
    /**
     * @test
     */
    public function _未ログイン状態の時は、空文字を返却する()
    {
      $response = $this->json('GET', route('user'));
      
      $response->assertStatus(200);
      $this->assertEquals("", $response->content());
    }
}
